"""Add registration_deadline to Event

Revision ID: 330b62bb59a0
Revises: 48c535158d1d
Create Date: 2025-04-16 20:13:52.833600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '330b62bb59a0'
down_revision = '48c535158d1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_deadline', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('registration_deadline')

    # ### end Alembic commands ###
