"""Add profile fields to User model

Revision ID: 554772e58318
Revises: 330b62bb59a0
Create Date: 2025-04-17 03:47:20.529013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '554772e58318'
down_revision = '330b62bb59a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('student_id', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('profile_image', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_image')
        batch_op.drop_column('student_id')
        batch_op.drop_column('department')
        batch_op.drop_column('bio')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
