"""Add admin_viewed field to Registration model

Revision ID: 7de75caff2f6
Revises: 554772e58318
Create Date: 2025-04-17 05:19:20.322237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7de75caff2f6'
down_revision = '554772e58318'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_viewed', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile_image',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile_image',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.drop_column('admin_viewed')

    # ### end Alembic commands ###
